/**
 * Per-Elementor-widget selector profiles.
 *
 * Each preset maps to:
 *   - The Elementor widget type (used in the container selector)
 *   - The CSS selectors actually inside that widget (used for the
 *     CSS-selectors list shown in the Preview pane)
 *   - Human-readable notes describing the layout
 *   - A canonical `treeTemplate` describing the recursive widget hierarchy
 *     the GSAP code is expected to address. The AX-style signature in
 *     `dspy-signature.ts` asks the LLM to instantiate this template
 *     (filling in `props.text` / `props.src` / `props.label` and the
 *     `state.count` for the carousel/pagination containers) and emit the
 *     resulting tree as JSON.
 *
 * Selector strategy (CRITICAL — fixes the "dead IDs" bug):
 *   - REPEATING children (slides, dots, cards, columns) → `className` field
 *     in the tree, querying via `querySelectorAll('.foo')`. The tree describes
 *     the structural template ONCE; instances are addressed by class + index.
 *   - ONE-OFF elements (root containers, progress labels) → `id` field. The
 *     user must set these in Elementor's Advanced tab; Elementor does not
 *     auto-generate unique ids.
 *
 * For testimonial carousel specifically, the inner classes are Swiper's stable
 * classes (`.swiper`, `.swiper-slide`, `.swiper-pagination-bullet`, etc.) —
 * these exist automatically when the Elementor "Slides" widget is dropped
 * on the page.
 */

import type { ElementorWidget } from './elementor-widget';

export interface WidgetProfile {
  widgetType: string;
  width: string;
  breakpoint: string;
  notes: string;
  /** Selectors the code will actually query, in priority order. */
  selectors: string[];
  /**
   * Canonical recursive widget tree. Repeating children have `className`
   * (no `id`). One-off elements have `id`. Both is invalid (would warn).
   */
  treeTemplate: ElementorWidget;
  /**
   * Repeating-subtree metadata — tells the LLM how many siblings to expect
   * for each repeating container (slide count, dot count, etc.).
   */
  repeats?: Array<{
    /** Parent className (or id) under which the repeated children live. */
    parentKey: string;
    /** Whether parentKey is an id (true) or className (false). */
    parentIsId: boolean;
    /** Class name shared by all repeating siblings. */
    childClassName: string;
    /** Default count if the intent doesn't specify one. */
    defaultCount: number;
    /** Human label for the repeat (e.g. "slide", "dot", "card"). */
    label: string;
  }>;
}

// ─── Testimonial (Elementor Slides widget = Swiper under the hood) ─────────
// Inner classes here are Swiper's own (stable, auto-generated by Swiper JS).

const TESTIMONIAL_TREE: ElementorWidget = {
  id: 'testimonial-swiper',
  kind: 'Container',
  label: 'Testimonial carousel',
  layout: 'flex column',
  children: [
    {
      className: 'swiper',
      kind: 'Container',
      label: 'Swiper wrapper',
      layout: 'flex row',
      children: [
        {
          className: 'swiper-slide',
          kind: 'Container',
          label: 'Slide',
          layout: 'absolute overlay',
          children: [
            { className: 'elementor-testimonial-content', kind: 'Text', label: 'Quote', props: { text: '...' } },
            { className: 'elementor-testimonial-name', kind: 'Heading', label: 'Author name', props: { text: '...' } },
            { className: 'elementor-testimonial-title', kind: 'Text', label: 'Author role', props: { text: '...' } },
            { className: 'elementor-testimonial-image', kind: 'Image', label: 'Avatar', props: { src: '...' } },
          ],
        },
      ],
    },
    {
      className: 'swiper-pagination',
      kind: 'Container',
      label: 'Pagination bullets',
      layout: 'flex row',
      children: [
        {
          className: 'swiper-pagination-bullet',
          kind: 'Icon',
          label: 'Bullet (first copy is active=true, rest active=false; Swiper auto-toggles .swiper-pagination-bullet-active at runtime)',
          state: { active: true },
        },
      ],
    },
    { className: 'swiper-button-prev', kind: 'Button', label: 'Previous slide' },
    { className: 'swiper-button-next', kind: 'Button', label: 'Next slide' },
  ],
};

// ─── Hero (custom Container layout — user sets classes in Elementor) ───────

const HERO_TREE: ElementorWidget = {
  className: 'hero-section',
  kind: 'Container',
  label: 'Hero section',
  layout: 'flex column',
  children: [
    { className: 'hero-bg', kind: 'Image', label: 'Background image', props: { src: '...' } },
    { className: 'hero-scrim', kind: 'Container', label: 'Gradient overlay', layout: 'absolute scrim' },
    {
      className: 'hero-content',
      kind: 'Container',
      label: 'Content card',
      layout: 'flex column, w50, side-by-side at lg-2',
      children: [
        { className: 'hero-eyebrow', kind: 'Text', label: 'Eyebrow', props: { text: '...' } },
        { className: 'hero-title', kind: 'Heading', label: 'Title', props: { text: '...' } },
        { className: 'hero-desc', kind: 'Text', label: 'Description', props: { text: '...' } },
        { className: 'hero-cta', kind: 'Button', label: 'Call to action', props: { label: '...', href: '#' } },
      ],
    },
  ],
};

// ─── Cards (Elementor Icon Box widget — auto-class) ────────────────────────

const cardChild = (): ElementorWidget => ({
  className: 'elementor-icon-box',
  kind: 'Container',
  label: 'Feature card',
  layout: 'flex column',
  children: [
    { className: 'elementor-icon', kind: 'Icon', label: 'Card icon' },
    { className: 'elementor-icon-box-title', kind: 'Heading', label: 'Card title', props: { text: '...' } },
    { className: 'elementor-icon-box-description', kind: 'Text', label: 'Card description', props: { text: '...' } },
  ],
});

const CARDS_TREE: ElementorWidget = {
  id: 'cards-grid',
  kind: 'Container',
  label: 'Feature cards grid',
  layout: 'flex row wrap',
  children: [cardChild()],
};

// ─── Pricing (Elementor Price Table — auto-class) ──────────────────────────

const pricingChild = (): ElementorWidget => ({
  className: 'elementor-price-table',
  kind: 'Container',
  label: 'Pricing column',
  layout: 'flex column',
  children: [
    { className: 'elementor-price-table__header', kind: 'Heading', label: 'Plan name', props: { text: '...' } },
    { className: 'elementor-price-table__price', kind: 'Heading', label: 'Price', props: { text: '...' } },
    { className: 'elementor-price-table__features', kind: 'Text', label: 'Feature list', props: { text: '...' } },
    { className: 'elementor-price-table__button', kind: 'Button', label: 'Plan CTA', props: { label: '...' } },
  ],
});

const PRICING_TREE: ElementorWidget = {
  id: 'pricing-grid',
  kind: 'Container',
  label: 'Pricing table row',
  layout: 'flex row',
  children: [pricingChild()],
};

// ─── Gallery (Elementor Image Gallery — auto-class) ────────────────────────

const GALLERY_TREE: ElementorWidget = {
  id: 'gallery-grid',
  kind: 'Container',
  label: 'Image gallery',
  layout: 'flex row wrap',
  children: [
    {
      className: 'gallery-item',
      kind: 'Image',
      label: 'Gallery image',
      props: { src: '...' },
    },
  ],
};

// ─── Counter (Elementor Counter widget — auto-class) ────────────────────────

const counterChild = (): ElementorWidget => ({
  className: 'elementor-counter',
  kind: 'Container',
  label: 'Stat cell',
  layout: 'flex column',
  children: [
    { className: 'elementor-counter-number', kind: 'Heading', label: 'Stat number', props: { text: '0' } },
    { className: 'elementor-counter-label', kind: 'Text', label: 'Stat label', props: { text: '...' } },
  ],
});

const COUNTER_TREE: ElementorWidget = {
  id: 'counter-row',
  kind: 'Container',
  label: 'Stats counter row',
  layout: 'flex row',
  children: [counterChild()],
};

// ─── Profile registry ──────────────────────────────────────────────────────

export const WIDGET_PROFILES: Record<string, WidgetProfile> = {
  testimonial: {
    widgetType: 'slides',
    width: 'w50',
    breakpoint: 'lg-2',
    notes:
      'Two-column testimonial carousel. Elementor Slides widget ships a live Swiper instance that owns navigation/clicks/autoplay/transitions. Script must hook Swiper events (root.swiper.on("slideChangeTransitionEnd")), NOT add its own click listeners to .swiper-button-* / .swiper-pagination-bullet. Inner classes are Swiper-stable.',
    selectors: [
      '.elementor-element.elementor-widget-slides',
      '.elementor-element.elementor-widget-slides .swiper',
      '.elementor-element.elementor-widget-slides .swiper-slide',
      '.elementor-element.elementor-widget-slides .elementor-testimonial-content',
      '.elementor-element.elementor-widget-slides .elementor-testimonial-name',
    ],
    treeTemplate: TESTIMONIAL_TREE,
    repeats: [
      { parentKey: 'swiper', parentIsId: false, childClassName: 'swiper-slide', defaultCount: 3, label: 'slide' },
      { parentKey: 'swiper-pagination', parentIsId: false, childClassName: 'swiper-pagination-bullet', defaultCount: 3, label: 'bullet' },
    ],
  },

  hero: {
    widgetType: 'heading',
    width: 'w100',
    breakpoint: 'lg-1',
    notes: 'Full-width hero section. User sets .hero-* classes in Elementor Advanced tab.',
    selectors: [
      '.elementor-element.elementor-widget-heading',
      '.elementor-element.elementor-widget-heading .elementor-heading-title',
      '.elementor-element.elementor-widget-heading .elementor-widget-theme-content-wrapper p',
      '.elementor-element.elementor-widget-button .elementor-button',
    ],
    treeTemplate: HERO_TREE,
  },

  cards: {
    widgetType: 'icon-box',
    width: 'w33',
    breakpoint: 'lg-4',
    notes: 'Three-column feature card grid (Elementor Icon Box widget — auto-class per card).',
    selectors: [
      '.elementor-element.elementor-widget-icon-box',
      '.elementor-element.elementor-widget-icon-box .elementor-icon-box-wrapper',
      '.elementor-element.elementor-widget-icon-box .elementor-icon-box-title',
      '.elementor-element.elementor-widget-icon-box .elementor-icon-box-description',
    ],
    treeTemplate: CARDS_TREE,
    repeats: [
      { parentKey: 'cards-grid', parentIsId: true, childClassName: 'elementor-icon-box', defaultCount: 6, label: 'card' },
    ],
  },

  pricing: {
    widgetType: 'price-table',
    width: 'w25',
    breakpoint: 'lg-3',
    notes: 'Four-column pricing table (Elementor Price Table — auto-class per column).',
    selectors: [
      '.elementor-element.elementor-widget-price-table',
      '.elementor-element.elementor-widget-price-table .elementor-price-table',
      '.elementor-element.elementor-widget-price-table .elementor-price-table__header',
      '.elementor-element.elementor-widget-price-table .elementor-price-table__price',
    ],
    treeTemplate: PRICING_TREE,
    repeats: [
      { parentKey: 'pricing-grid', parentIsId: true, childClassName: 'elementor-price-table', defaultCount: 3, label: 'plan' },
    ],
  },

  gallery: {
    widgetType: 'image-gallery',
    width: 'w33',
    breakpoint: 'lg-4',
    notes: 'Three-column image gallery (Elementor Image Gallery — auto-class per item).',
    selectors: [
      '.elementor-element.elementor-widget-image-gallery',
      '.elementor-element.elementor-widget-image-gallery .gallery-item',
      '.elementor-element.elementor-widget-image-gallery img',
    ],
    treeTemplate: GALLERY_TREE,
    repeats: [
      { parentKey: 'gallery-grid', parentIsId: true, childClassName: 'gallery-item', defaultCount: 6, label: 'image' },
    ],
  },

  counter: {
    widgetType: 'counter',
    width: 'w25',
    breakpoint: 'lg-3',
    notes: 'Four-stat counter row (Elementor Counter widget — auto-class per cell).',
    selectors: [
      '.elementor-element.elementor-widget-counter',
      '.elementor-element.elementor-widget-counter .elementor-counter',
      '.elementor-element.elementor-widget-counter .elementor-counter-number',
      '.elementor-element.elementor-widget-counter .elementor-counter-label',
    ],
    treeTemplate: COUNTER_TREE,
    repeats: [
      { parentKey: 'counter-row', parentIsId: true, childClassName: 'elementor-counter', defaultCount: 4, label: 'stat' },
    ],
  },
};

export type WidgetKey = keyof typeof WIDGET_PROFILES;

/**
 * Pick the right widget profile based on intent keywords.
 */
export function selectWidgetProfile(intent: string): WidgetProfile {
  const lc = intent.toLowerCase();

  if (lc.includes('testimonial') || lc.includes('quote')) return WIDGET_PROFILES.testimonial;
  if (lc.includes('hero')) return WIDGET_PROFILES.hero;
  if (lc.includes('card') || lc.includes('feature')) return WIDGET_PROFILES.cards;
  if (lc.includes('pricing') || lc.includes('price')) return WIDGET_PROFILES.pricing;
  if (lc.includes('gallery') || lc.includes('image')) return WIDGET_PROFILES.gallery;
  if (lc.includes('counter') || lc.includes('stat') || lc.includes('number')) return WIDGET_PROFILES.counter;

  // Default fallback — hero section (most generic)
  return WIDGET_PROFILES.hero;
}

/**
 * Pick the appropriate repeat count from the user's prose. Recognises leading
 * cardinal digits, then a small set of synonyms). Returns the profile's
 * defaultCount when no count is found in the intent.
 */
export function inferRepeatCount(intent: string, defaultCount: number): number {
  const lc = intent.toLowerCase();
  // First try a digit: "4 slides", "three cards", "six testimonials"
  const digit = lc.match(/\b(\d{1,2})\b/);
  if (digit) {
    const n = parseInt(digit[1], 10);
    if (n >= 1 && n <= 24) return n;
  }
  const wordToN: Record<string, number> = {
    one: 1, two: 2, three: 3, four: 4, five: 5, six: 6,
    seven: 7, eight: 8, nine: 9, ten: 10,
  };
  for (const [w, n] of Object.entries(wordToN)) {
    if (lc.includes(`${w} `) || lc.includes(`${w}-`) || lc.endsWith(w)) {
      return n;
    }
  }
  return defaultCount;
}